//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solum {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solum.MessagesResource", typeof(MessagesResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o valor de Al.
        /// </summary>
        internal static string AnaliseAlNull {
            get {
                return ResourceManager.GetString("AnaliseAlNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o valor para Areia.
        /// </summary>
        internal static string AnaliseAreiaNull {
            get {
                return ResourceManager.GetString("AnaliseAreiaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o valor para Argila.
        /// </summary>
        internal static string AnaliseArgilaNull {
            get {
                return ResourceManager.GetString("AnaliseArgilaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o valor de Ca.
        /// </summary>
        internal static string AnaliseCaNull {
            get {
                return ResourceManager.GetString("AnaliseCaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data selecionada não pode ser utilizada.
        /// </summary>
        internal static string AnaliseDataInvalida {
            get {
                return ResourceManager.GetString("AnaliseDataInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma fazenda primeiro.
        /// </summary>
        internal static string AnaliseFazendaNull {
            get {
                return ResourceManager.GetString("AnaliseFazendaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o valor de H.
        /// </summary>
        internal static string AnaliseHNull {
            get {
                return ResourceManager.GetString("AnaliseHNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo de identificação da análise.
        /// </summary>
        internal static string AnaliseIdentificacaoNull {
            get {
                return ResourceManager.GetString("AnaliseIdentificacaoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o valor de K.
        /// </summary>
        internal static string AnaliseKNull {
            get {
                return ResourceManager.GetString("AnaliseKNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o valor de Mg.
        /// </summary>
        internal static string AnaliseMgNull {
            get {
                return ResourceManager.GetString("AnaliseMgNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o valor para Matéria Orgânica.
        /// </summary>
        internal static string AnaliseMoNull {
            get {
                return ResourceManager.GetString("AnaliseMoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o valor do PH.
        /// </summary>
        internal static string AnalisePhNull {
            get {
                return ResourceManager.GetString("AnalisePhNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o valor de P.
        /// </summary>
        internal static string AnalisePNull {
            get {
                return ResourceManager.GetString("AnalisePNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o valor para Silte.
        /// </summary>
        internal static string AnaliseSilteNull {
            get {
                return ResourceManager.GetString("AnaliseSilteNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados da análise salvos com sucesso.
        /// </summary>
        internal static string AnaliseSucesso {
            get {
                return ResourceManager.GetString("AnaliseSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma fazenda para poder selecionar o talhão.
        /// </summary>
        internal static string AnaliseTalhaoNull {
            get {
                return ResourceManager.GetString("AnaliseTalhaoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha todos os campos .
        /// </summary>
        internal static string CamposVazios {
            get {
                return ResourceManager.GetString("CamposVazios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As informações foram salvas.
        /// </summary>
        internal static string DadosSalvos {
            get {
                return ResourceManager.GetString("DadosSalvos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o estado e a cidade de endereço da fazenda.
        /// </summary>
        internal static string FazendaCadastroCidadeVazia {
            get {
                return ResourceManager.GetString("FazendaCadastroCidadeVazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo de nome da fazenda.
        /// </summary>
        internal static string FazendaCadastroNomeVazio {
            get {
                return ResourceManager.GetString("FazendaCadastroNomeVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fazenda cadastrada com sucesso.
        /// </summary>
        internal static string FazendaCadastroSucesso {
            get {
                return ResourceManager.GetString("FazendaCadastroSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fazenda atualizada com sucesso.
        /// </summary>
        internal static string FazendaEdicaoSucesso {
            get {
                return ResourceManager.GetString("FazendaEdicaoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível remover fazenda: a fazenda possui análises. Remova as análises primeiro.
        /// </summary>
        internal static string FazendaRemocaoFalha {
            get {
                return ResourceManager.GetString("FazendaRemocaoFalha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fazenda removida com sucesso.
        /// </summary>
        internal static string FazendaRemocaoSucesso {
            get {
                return ResourceManager.GetString("FazendaRemocaoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu e-mail ou senha estão incorretos.
        /// </summary>
        internal static string LoginCredenciaisErradas {
            get {
                return ResourceManager.GetString("LoginCredenciaisErradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha os campos de Usuário e Senha..
        /// </summary>
        internal static string LoginCredenciaisNulas {
            get {
                return ResourceManager.GetString("LoginCredenciaisNulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login com sucesso.
        /// </summary>
        internal static string LoginSucesso {
            get {
                return ResourceManager.GetString("LoginSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FazendaSelecionada.
        /// </summary>
        internal static string McFazendaSelecionada {
            get {
                return ResourceManager.GetString("McFazendaSelecionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TalhaoSelecionado.
        /// </summary>
        internal static string McTalhaoSelecionado {
            get {
                return ResourceManager.GetString("McTalhaoSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Função não implementada ainda.
        /// </summary>
        internal static string NaoImplementado {
            get {
                return ResourceManager.GetString("NaoImplementado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível conectar ao servidor.
        /// </summary>
        internal static string ServidorIndisponivel {
            get {
                return ResourceManager.GetString("ServidorIndisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo com nome do talhão.
        /// </summary>
        internal static string TalhaoCadastroNomeVazio {
            get {
                return ResourceManager.GetString("TalhaoCadastroNomeVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talhão cadastrado com sucesso.
        /// </summary>
        internal static string TalhaoCadastroSucesso {
            get {
                return ResourceManager.GetString("TalhaoCadastroSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talhão atualizado com sucesso.
        /// </summary>
        internal static string TalhaoEdicaoSucesso {
            get {
                return ResourceManager.GetString("TalhaoEdicaoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível remover o talhão: o talhão possui análises. Remova as análises primeiro.
        /// </summary>
        internal static string TalhaoRemocaoFalha {
            get {
                return ResourceManager.GetString("TalhaoRemocaoFalha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talhao removido com sucesso.
        /// </summary>
        internal static string TalhaoRemocaoSucesso {
            get {
                return ResourceManager.GetString("TalhaoRemocaoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o estado e a cidade que reside.
        /// </summary>
        internal static string UsuarioCadastroCidadeNula {
            get {
                return ResourceManager.GetString("UsuarioCadastroCidadeNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu e-mail não está no formato correto.
        /// </summary>
        internal static string UsuarioCadastroEmailInvalido {
            get {
                return ResourceManager.GetString("UsuarioCadastroEmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu cadastro não foi realizado com sucesso. Seu e-mail já está sendo utilizado.
        /// </summary>
        internal static string UsuarioCadastroFalhou {
            get {
                return ResourceManager.GetString("UsuarioCadastroFalhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua senha deve conter ao menos 6 caracteres.
        /// </summary>
        internal static string UsuarioCadastroSenhaCurta {
            get {
                return ResourceManager.GetString("UsuarioCadastroSenhaCurta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suas senhas não são iguais..
        /// </summary>
        internal static string UsuarioCadastroSenhasNaoConferem {
            get {
                return ResourceManager.GetString("UsuarioCadastroSenhasNaoConferem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu cadastro foi realizado com sucesso.
        /// </summary>
        internal static string UsuarioCadastroSucesso {
            get {
                return ResourceManager.GetString("UsuarioCadastroSucesso", resourceCulture);
            }
        }
    }
}
