// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Solum {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Solum.MessagesResource", typeof(MessagesResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AnaliseAlNull {
            get {
                return ResourceManager.GetString("AnaliseAlNull", resourceCulture);
            }
        }
        
        internal static string AnaliseAreiaNull {
            get {
                return ResourceManager.GetString("AnaliseAreiaNull", resourceCulture);
            }
        }
        
        internal static string AnaliseArgilaNull {
            get {
                return ResourceManager.GetString("AnaliseArgilaNull", resourceCulture);
            }
        }
        
        internal static string AnaliseCaNull {
            get {
                return ResourceManager.GetString("AnaliseCaNull", resourceCulture);
            }
        }
        
        internal static string AnaliseDataInvalida {
            get {
                return ResourceManager.GetString("AnaliseDataInvalida", resourceCulture);
            }
        }
        
        internal static string AnaliseFazendaNull {
            get {
                return ResourceManager.GetString("AnaliseFazendaNull", resourceCulture);
            }
        }
        
        internal static string AnaliseHNull {
            get {
                return ResourceManager.GetString("AnaliseHNull", resourceCulture);
            }
        }
        
        internal static string AnaliseIdentificacaoNull {
            get {
                return ResourceManager.GetString("AnaliseIdentificacaoNull", resourceCulture);
            }
        }
        
        internal static string AnaliseKNull {
            get {
                return ResourceManager.GetString("AnaliseKNull", resourceCulture);
            }
        }
        
        internal static string AnaliseMgNull {
            get {
                return ResourceManager.GetString("AnaliseMgNull", resourceCulture);
            }
        }
        
        internal static string AnaliseMoNull {
            get {
                return ResourceManager.GetString("AnaliseMoNull", resourceCulture);
            }
        }
        
        internal static string AnalisePhNull {
            get {
                return ResourceManager.GetString("AnalisePhNull", resourceCulture);
            }
        }
        
        internal static string AnalisePNull {
            get {
                return ResourceManager.GetString("AnalisePNull", resourceCulture);
            }
        }
        
        internal static string AnaliseSilteNull {
            get {
                return ResourceManager.GetString("AnaliseSilteNull", resourceCulture);
            }
        }
        
        internal static string AnaliseSucesso {
            get {
                return ResourceManager.GetString("AnaliseSucesso", resourceCulture);
            }
        }
        
        internal static string AnaliseTalhaoNull {
            get {
                return ResourceManager.GetString("AnaliseTalhaoNull", resourceCulture);
            }
        }
        
        internal static string CamposVazios {
            get {
                return ResourceManager.GetString("CamposVazios", resourceCulture);
            }
        }
        
        internal static string FazendaCadastroCidadeVazia {
            get {
                return ResourceManager.GetString("FazendaCadastroCidadeVazia", resourceCulture);
            }
        }
        
        internal static string FazendaCadastroNomeVazio {
            get {
                return ResourceManager.GetString("FazendaCadastroNomeVazio", resourceCulture);
            }
        }
        
        internal static string FazendaCadastroSucesso {
            get {
                return ResourceManager.GetString("FazendaCadastroSucesso", resourceCulture);
            }
        }
        
        internal static string FazendaEdicaoSucesso {
            get {
                return ResourceManager.GetString("FazendaEdicaoSucesso", resourceCulture);
            }
        }
        
        internal static string FazendaRemocaoFalha {
            get {
                return ResourceManager.GetString("FazendaRemocaoFalha", resourceCulture);
            }
        }
        
        internal static string FazendaRemocaoSucesso {
            get {
                return ResourceManager.GetString("FazendaRemocaoSucesso", resourceCulture);
            }
        }
        
        internal static string LoginCredenciaisErradas {
            get {
                return ResourceManager.GetString("LoginCredenciaisErradas", resourceCulture);
            }
        }
        
        internal static string LoginCredenciaisNulas {
            get {
                return ResourceManager.GetString("LoginCredenciaisNulas", resourceCulture);
            }
        }
        
        internal static string LoginSucesso {
            get {
                return ResourceManager.GetString("LoginSucesso", resourceCulture);
            }
        }
        
        internal static string McFazendaSelecionada {
            get {
                return ResourceManager.GetString("McFazendaSelecionada", resourceCulture);
            }
        }
        
        internal static string McTalhaoSelecionado {
            get {
                return ResourceManager.GetString("McTalhaoSelecionado", resourceCulture);
            }
        }
        
        internal static string NaoImplementado {
            get {
                return ResourceManager.GetString("NaoImplementado", resourceCulture);
            }
        }
        
        internal static string ServidorIndisponivel {
            get {
                return ResourceManager.GetString("ServidorIndisponivel", resourceCulture);
            }
        }
        
        internal static string TalhaoCadastroNomeVazio {
            get {
                return ResourceManager.GetString("TalhaoCadastroNomeVazio", resourceCulture);
            }
        }
        
        internal static string TalhaoCadastroSucesso {
            get {
                return ResourceManager.GetString("TalhaoCadastroSucesso", resourceCulture);
            }
        }
        
        internal static string TalhaoEdicaoSucesso {
            get {
                return ResourceManager.GetString("TalhaoEdicaoSucesso", resourceCulture);
            }
        }
        
        internal static string TalhaoRemocaoFalha {
            get {
                return ResourceManager.GetString("TalhaoRemocaoFalha", resourceCulture);
            }
        }
        
        internal static string TalhaoRemocaoSucesso {
            get {
                return ResourceManager.GetString("TalhaoRemocaoSucesso", resourceCulture);
            }
        }
        
        internal static string UsuarioCadastroCidadeNula {
            get {
                return ResourceManager.GetString("UsuarioCadastroCidadeNula", resourceCulture);
            }
        }
        
        internal static string UsuarioCadastroEmailInvalido {
            get {
                return ResourceManager.GetString("UsuarioCadastroEmailInvalido", resourceCulture);
            }
        }
        
        internal static string UsuarioCadastroFalhou {
            get {
                return ResourceManager.GetString("UsuarioCadastroFalhou", resourceCulture);
            }
        }
        
        internal static string UsuarioCadastroSenhaCurta {
            get {
                return ResourceManager.GetString("UsuarioCadastroSenhaCurta", resourceCulture);
            }
        }
        
        internal static string UsuarioCadastroSenhasNaoConferem {
            get {
                return ResourceManager.GetString("UsuarioCadastroSenhasNaoConferem", resourceCulture);
            }
        }
        
        internal static string UsuarioCadastroSucesso {
            get {
                return ResourceManager.GetString("UsuarioCadastroSucesso", resourceCulture);
            }
        }
        
        internal static string DadosSalvos {
            get {
                return ResourceManager.GetString("DadosSalvos", resourceCulture);
            }
        }
        
        internal static string ExpectativaNull {
            get {
                return ResourceManager.GetString("ExpectativaNull", resourceCulture);
            }
        }
        
        internal static string CulturaNull {
            get {
                return ResourceManager.GetString("CulturaNull", resourceCulture);
            }
        }
        
        internal static string CadastroSucesso {
            get {
                return ResourceManager.GetString("CadastroSucesso", resourceCulture);
            }
        }
        
        internal static string CadastroFalha {
            get {
                return ResourceManager.GetString("CadastroFalha", resourceCulture);
            }
        }
        
        internal static string V2Null {
            get {
                return ResourceManager.GetString("V2Null", resourceCulture);
            }
        }
        
        internal static string PRNTNull {
            get {
                return ResourceManager.GetString("PRNTNull", resourceCulture);
            }
        }
        
        internal static string ProfundidadeNull {
            get {
                return ResourceManager.GetString("ProfundidadeNull", resourceCulture);
            }
        }
        
        internal static string PRNTInvalido {
            get {
                return ResourceManager.GetString("PRNTInvalido", resourceCulture);
            }
        }
        
        internal static string ExcluirConfirmacao {
            get {
                return ResourceManager.GetString("ExcluirConfirmacao", resourceCulture);
            }
        }
        
        internal static string FazendaRemocaoBloqueio {
            get {
                return ResourceManager.GetString("FazendaRemocaoBloqueio", resourceCulture);
            }
        }
        
        internal static string TalhaoRemocaoBloqueio {
            get {
                return ResourceManager.GetString("TalhaoRemocaoBloqueio", resourceCulture);
            }
        }
        
        internal static string InterpretacaoNull {
            get {
                return ResourceManager.GetString("InterpretacaoNull", resourceCulture);
            }
        }
        
        internal static string CalagemNull {
            get {
                return ResourceManager.GetString("CalagemNull", resourceCulture);
            }
        }
        
        internal static string CorretivaNull {
            get {
                return ResourceManager.GetString("CorretivaNull", resourceCulture);
            }
        }
        
        internal static string SemeaduraNull {
            get {
                return ResourceManager.GetString("SemeaduraNull", resourceCulture);
            }
        }
        
        internal static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
    }
}
